//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int Id { get; set; }
        public int CarId { get; set; }
        public string UserId { get; set; }
        public System.DateTime PickUpDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public Nullable<System.DateTime> ActualReturnDate { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
