//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerSide.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentCarDBEntities : DbContext
    {
        public RentCarDBEntities()
            : base("name=RentCarDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Rental> Rental { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<CarType> CarType { get; set; }
    }
}
